### ISSUE TITLE
Thread blocked calling knative REST

### ISSUE THREAD

**Issue by makandre** [apache/camel-k-runtime#513] opened 2020-09-29 13:38 UTC
@makandre commented on [Tue Sep 29 2020](https://github.com/apache/camel-k/issues/1720)

I'm doing a `.to("rest:...")` call, and because the target endpoint is a knative service, it takes some time for it to spin up. When that happens I get these thread blocked errors:

```
Sep 29, 2020 1:23:41 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 10006 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
```

I'm using camel-k `1.1.0`

**Comment by lburgazzoli** [comment] 2020-09-30 10:06
@makandre mind posting the complete route definition ?

**Comment by makandre** [comment] 2020-09-30 11:23
Sure, my route is acting as a proxy to another knative service

```
restConfiguration().setHost("a knative .svc.cluster.local host")

rest("/results")
    .get("/{id}")
    .to("direct:results");

from("direct:results")
    .removeHeaders("*", "CamelHttpPath")
    .to("rest:get:?bridgeEndpoint=true");
```

**Comment by lburgazzoli** [comment] 2020-09-30 11:49
What runtime are you on ? the default one or quarkus ?

**Comment by makandre** [comment] 2020-09-30 11:52
How do I check that?  I didn't configure specifically for quarkus, so I assume I'm using default.

**Comment by lburgazzoli** [comment] 2020-09-30 11:52
ok, thx I think I know what the issue is now

**Comment by lburgazzoli** [comment] 2020-09-30 15:13
I'm working on a fix but may take a while to get incorporated in camel-k.
In the meantime you can register a bean to the registry to configure the Vert.x instance, like:


```java
@org.apache.camel.BindToRegistry
public io.vertx.core.VertxOptions vertxOptions() {
    return new io.vertx.core.VertxOptions()
        .setMaxEventLoopExecuteTime(10)
        .setMaxEventLoopExecuteTimeUnit(TimeUnit.SECONDS));
}
```

**Comment by makandre** [comment] 2020-10-15 12:16
Hi @lburgazzoli, I just updated to camel-k 1.2, and the above workaround you gave me stopped working; my change of the timeout doesn't take affect and it's always uses the default 2000ms

**Comment by lburgazzoli** [comment] 2020-10-15 13:08
yes, you now need to extends a route builder in any case

**Comment by makandre** [comment] 2020-10-15 13:29
I don't quite follow.  The class where I've placed that `vertxOptions` method does extend `RouteBuilder`

**Comment by lburgazzoli** [comment] 2020-10-15 13:40
ah yeah sorry, we have switched to quarkus as default, let me see how it can be fixed in that case

**Comment by makandre** [comment] 2020-10-15 14:37
I might be setting this wrong I got:

```
Error configuring property: camel.component.quarkus.vertx.max-event-loop-execute-time because cannot find component with name quarkus. Make sure you have the component on the classpath
```

I added `camel-quarkus-vertx` as a dependency

**Comment by lburgazzoli** [comment] 2020-10-15 14:41
You only need:

    quarkus.vertx.max-event-loop-execute-time

and you should need to add any additional dependency

**Comment by makandre** [comment] 2020-10-15 14:55
Thank you, that worked.

**Comment by pjcubero** [comment] 2020-10-20 09:17
Dear @makandre, can you explain me how have done that? I have one integration that calls other knative channels, and I see the problem with the thread blocked lot of times, can you explain me how have you solved?

**Comment by makandre** [comment] 2020-10-20 11:12
Yes, I used the `vertxoption` method before camel-k 1.2 (when it wasn't using Quarkus).  I just defined the method as suggested above in the same `RouteBuilder` as my route definitions.  You don't need to call the method since it's using `@BindToRegistry`, Camel was able to figure it out.

**Comment by pjcubero** [comment] 2020-10-20 11:18
this way?

	@org.apache.camel.BindToRegistry
	public io.vertx.core.VertxOptions vertxOptions() {
		return new io.vertx.core.VertxOptions()
			.setMaxEventLoopExecuteTime(2000)
			.setMaxEventLoopExecuteTimeUnit(TimeUnit.SECONDS));
	}  
  
  @Override
  public void configure() throws Exception {

**Comment by makandre** [comment] 2020-10-20 11:23
Right.

**Comment by lburgazzoli** [comment] 2020-11-11 08:09
This should have been fixed upstream

**Closed** 2021-01-11 09:26 UTC
